add structured logger example app
dictu-lang/Dictu pull request #501
Opened 2021-12-29 04:38 UTC by briandowns

Signed-off-by: Brian Downs <brian.downs@gmail.com>

### Well detailed description of the change :

Adds a simple JSON structured logger.

Resolves: #

#

### Type of change:

- [ ] Bug fix

- [ ] New feature

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#

### Housekeeping

- [ ] Tests have been updated to reflect the changes done within this PR (if applicable).

- [ ] Documentation has been updated to reflect the changes done within this PR (if applicable).

#

### Preview (Screenshots) :

2021-12-29 15:54 UTC, Jason2605 requested changes
Massively nitpick comments really (sorry) but just a few changes!

I really like this example though, thanks!

2021-12-29 15:54 UTC, Jason2605 commented on examples/structured_logger.du
> +        var j = JSON.parse(this.entry.toString());
```suggestion
        const j = JSON.parse(this.entry.toString());
```

2021-12-29 15:54 UTC, Jason2605 commented on examples/structured_logger.du
> +            with(this.output, "w") {
We don't want to overwrite our logs!

```suggestion
            with(this.output, "a") {
```

2021-12-29 15:54 UTC, Jason2605 commented on examples/structured_logger.du
> +    var log = Log();
```suggestion
    const log = Log();
```

2021-12-29 16:17 UTC, Jason2605 commented
Hm interestingly the CI/CD is exiting with 1. Not entirely sure why, it doesn't for me locally...

2021-12-29 16:39 UTC, briandowns commented
> Hm interestingly the CI/CD is exiting with 1. Not entirely sure why, it doesn't for me locally...

Strange. it's doing the same for me as well. (macOS)

2021-12-29 17:31 UTC, Jason2605 commented
> > Hm interestingly the CI/CD is exiting with 1. Not entirely sure why, it doesn't for me locally...
> 
> Strange. it's doing the same for me as well. (macOS)

Hm. I'm on MacOS as well and it seems to exit as normal..

2021-12-29 18:08 UTC, briandowns commented
@Jason2605 Looks like it was the exit call at the end of the example. Good to go.

2021-12-29 18:09 UTC, Jason2605 commented
> @Jason2605 Looks like it was the exit call at the end of the example. Good to go.

Thats made me a little uneasy haha. I tested locally and on an ubuntu VM and it didn't seem to exit with code 1. An exit(0) call also shouldn't have made it exit with code 1 🤯

2021-12-30 23:27 UTC, Jason2605 commented
Ahhh I know why it's giving exit code 1. The CI/CD is expecting the debug message "Total bytes lost: 0" but the `System.exit(0)` call is exiting out the VM early and not displaying this message.

2021-12-30 23:27 UTC, merged